### ISSUE TITLE
Error with webpack loaders after CSS integration

### ISSUE THREAD

**Issue by hzhu** [hzhu/weworkhostels-v2#10]
![screen shot 2016-01-14 at 12 22 37 am](https://cloud.githubusercontent.com/assets/1811365/12319102/9870dc4c-ba54-11e5-8d4d-9102ae576b89.png)

Error only seen on production website. Currently unable to replicate locally.

**Comment by hzhu** [comment]
Still not sure why we DON'T get this error locally.

Found this in the snap-ci build logs. There's an `ReferenceError: Promise is not defined`
 when we run `webpack` to build our bundle.

```
> webpack -p && babel server.js --presets es2015 --out-file server-compiled.js

Hash: bd1e8747c7d81daf6486
Version: webpack 1.12.11
Time: 19447ms
    Asset    Size  Chunks             Chunk Names
bundle.js  421 kB       0  [emitted]  main
    + 263 hidden modules

WARNING in bundle.js from UglifyJs
Condition always true [./~/react/lib/ReactMount.js:764,0]
Condition always true [./~/react/lib/findDOMNode.js:46,0]
Condition always true [./~/react/lib/instantiateReactComponent.js:80,0]
Dropping unreachable code [./~/react/lib/shouldUpdateReactComponent.js:40,0]
Condition always true [./~/react/lib/traverseAllChildren.js:158,0]
Condition always true [./~/history/lib/createMemoryHistory.js:69,0]
Side effects in initialization of unused variable state [./~/react-router/lib/Link.js:106,0]
Condition always true [./~/react-router/lib/Redirect.js:49,0]
Side effects in initialization of unused variable key [./src/client/js/components/Input.js:11,8]
Side effects in initialization of unused variable jobs [./src/client/js/components/JobListings.js:6,12]
Side effects in initialization of unused variable actions [./src/client/js/components/JobListings.js:7,12]
Side effects in initialization of unused variable actions [./src/client/js/components/Post.js:6,12]
Condition always true [./~/react-router/lib/IndexRedirect.js:49,0]
Condition always true [./~/react-router/lib/IndexRoute.js:46,0]
Condition always true [./~/react-router/lib/Route.js:50,0]
Condition always true [./~/react/lib/ReactDOMComponent.js:907,0]
Dropping side-effect-free statement [./~/react/lib/ReactEventListener.js:72,0]
Dropping unused function handleTopLevelWithPath [./~/react/lib/ReactEventListener.js:98,0]
Dropping unused variable DOCUMENT_FRAGMENT_NODE_TYPE [./~/react/lib/ReactEventListener.js:26,0]
Side effects in initialization of unused variable sourceMap [./~/style-loader/addStyles.js:214,0]
Side effects in initialization of unused variable media [./~/style-loader/addStyles.js:232,0]
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always false [./~/style-loader!./~/css-loader!./~/postcss-loader!./~/sass-loader!!./src/client/scss/base.scss:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/postcss-loader!./~/sass-loader!!./src/client/scss/base.scss:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/postcss-loader!./~/sass-loader!!./src/client/scss/base.scss:7,0]

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/client/scss/base.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/var/snap-ci/repo/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/var/snap-ci/repo/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/var/snap-ci/repo/node_modules/postcss-loader/index.js:47:32)
 @ ./src/client/scss/base.scss 4:14-176
```

**Comment by hzhu** [comment]
https://github.com/webpack/css-loader/issues/145 

Fixed. Realized the issue was that our NodeJS version in our CI environment was 0.10x. Making it 4.1.1 fixed this issue. 4.1.1 has the Promise defined. No polyfill needed.
